package ui

// TODO: Can start putting them here and break them off and move them to
// pacakges from here
var Symbols = map[string]map[string]string{
	"status": map[string]string{
		"info":    "ℹ ",
		"success": "✔ ",
		"warning": "⚠ ",
		"error":   "✖ ",
	},
	"emoticons": map[string]string{
		"sad":   "☹",
		"happy": "☺",
	},
	"shogi": map[string]string{
		"white": "☖",
		"black": "☗",
	},
	"diamond_checkbox": map[string]string{
		"false": "◇",
		"true":  "◈",
		"solid": "◆",
	},
	"radio": map[string]string{
		"true":   "◉",
		"false":  "◯",
		"filled": "●",
		"dotted": "◌",
	},
	"checkbox": map[string]string{
		"xed":     "☒",
		"rounded": "▢",
		"checked": "☑",
		"filled":  "◼",
		"false":   "☐",
	},
	"arrows": map[string]string{
		"up":    "↑",
		"down":  "↓",
		"left":  "←",
		"right": "→",
	},
	"fraction": map[string]string{
		"one_half":       "½",
		"one_third":      "⅓",
		"one_quarter":    "¼",
		"one_fifth":      "⅕",
		"one_sixth":      "⅙",
		"one_seventh":    "⅐",
		"one_eighth":     "⅛",
		"one_ninth":      "⅑",
		"one_tenth":      "⅒",
		"two_thirds":     "⅔",
		"two_fifths":     "⅖",
		"three_quarters": "¾",
		"three_fifths":   "⅗",
		"three_eighths":  "⅜",
		"four_fifths":    "⅘",
		"five_sixths":    "⅚",
		"five_eighths":   "⅝",
		"seven_eighths":  "⅞",
	},
	"player": map[string]string{
		"stop":                "◼",
		"play":                "▶",
		"repeat":              "🔁",
		"repeat_once":         "🔂",
		"random":              "🔀",
		"mute":                "🔇",
		"mute_volume":         "🔈",
		"decrease_volume":     "🔉",
		"increase_volume":     "🔊 ",
		"decrease_brightness": "🔅",
		"increase_brightness": "🔆",
	},
	"math": map[string]string{
		"pi":       "π ",
		"omega":    "Ω ",
		"theta":    "Θ ",
		"beta":     "β ",
		"delta":    "δ ",
		"multiply": "✕",
	},
	"star": map[string]string{
		"filled": "★",
		"empty":  "☆",
	},
	"flag": map[string]string{
		"filled": "⚑",
		"empty":  "⚐",
	},
	"heart": map[string]string{
		"filled": "♥",
		"empty":  "♡",
	},
	"calendar": map[string]string{
		"spiral":   "🗓",
		"standard": "📅",
		"tear_off": "📆",
	},
	"security": map[string]string{
		"key":          "🔑",
		"lock_and_key": "🔐",
		"lock_closed":  "🔒",
		"lock_open":    "🔓",
	},
	"filesystem": map[string]string{
		"directory":      "📁",
		"directory_open": "📂",
		"editor":         "📝",
		"label":          "🏷",
	},
	"desktop": map[string]string{
		"home":               "🏠",
		"trash":              "🗑",
		"compress":           "🗜",
		"visible":            "👁",
		"pencil":             "✏",
		"writing":            "✍",
		"lower_right_pencil": "✎",
		"upper_right_pencil": " ✐",
		"stopped_hourglass":  "⌛",
		"active_hourglass":   "⏳",
	},
	"www": map[string]string{
		"link":                   "🔗",
		"europe_and_africa":      "🌍",
		"americas":               "🌎",
		"asia_and_oceania":       "🌏",
		"globe_with_meridians":   "🌐",
		"world_map":              "🗺",
		"anchor":                 "⚓",
		"wifi":                   "📶",
		"image":                  "🖼",
		"missing_image":          "⌧",
		"notifications":          "🔔",
		"disabled_notifications": "🔕",
		"bookmark":               "🔖",
		"tabs":                   "📑",
		"attach":                 "📎",
		"archive":                "🗃",
		"news":                   "📰",
		"pin":                    "📌",
		"email":                  "📧",
		"outbox":                 "📤",
		"inbox":                  "📥",
		"send":                   "📨",
		"receive":                "📩",
	},
	"book": map[string]string{
		"open":   "📖",
		"closed": "📕",
	},
	"keyboard": map[string]string{
		"windows":   "❖",
		"meta":      "◆",
		"shift":     "⇧",
		"helm":      "⎈",
		"capslock":  "⇪",
		"option":    "⌥",
		"alt":       "⎇",
		"command":   "⌘",
		"control":   "✲",
		"backspace": "⌫",
		"enter":     "⏎",
		"return":    "⏎",
		"menu":      "𝌆",
	},
	"sun": map[string]string{
		"filled": "☀",
		"empty":  "☼",
	},
	"musical": map[string]string{
		"quarter":        "♩",
		"eigth":          "♪",
		"violin":         "🎻",
		"saxophone":      "🎷",
		"guitar":         "🎸",
		"drum":           "🥁",
		"trumpet":        "🎺",
		"beamed_eigth":   "♫",
		"score":          "🎼",
		"slider":         "🎚",
		"knobs":          "🎛",
		"microphone":     "🎤",
		"headphone":      "🎧",
		"radio":          "📻",
		"multiple_notes": "🎶",
		"beamed_sixth":   "♬",
		"flat":           "♭",
		"natural":        "♮",
		"sharp":          "♯",
	},
	"weather": map[string]string{
		"sunny":        "☀",
		"cloudy":       "☁",
		"rainy":        "☂",
		"snowy":        "☃",
		"snowy2":       "🌨",
		"tornado":      "🌪",
		"foggy":        " 🌫",
		"rainbow":      "🌈",
		"stormy":       "⛈",
		"meteorshower": "☄",
	},
}
